### PR TITLE
fix: checkGetRelativeURL method with empty relative URI edge case, #70

### LINKED ISSUE #70: `index out of range [0] with length 0` at function `checkGetRelativeURL` when site url does not have .com
**Describe the bug**
This is a bug in code, not a bug SharePoint Server,
When site url is set to
```json
"siteUrl": "https://www.contoso.com/sites/test"
```
this function works fine, but when the site url is set like this (does not have .com, i don't know how it relates)
```json
"siteUrl": "https://www.contoso/sites/test"
```
the program panics at function
```go
// checkGetRelativeURL checks if URL is relative, prepends relative part if missed
func checkGetRelativeURL(relativeURI string, ctxURL string) string {
	// Prepend web relative URL to "Lists/ListPath" URIs
	if string([]rune(relativeURI)[0]) != "/" {
		absoluteURL := getPriorEndpoint(ctxURL, "/_api")
		relativeURL := getRelativeURL(absoluteURL)
		relativeURI = fmt.Sprintf("%s/%s", relativeURL, relativeURI)
	}
	return relativeURI
}
```

this is because the string `relativeURI` somehow becomes empty in the recursions, and `[]rune(relativeURI)[0]` becomes a null value, panicking the program, so I tried debugging it this way
```go
// checkGetRelativeURL checks if URL is relative, prepends relative part if missed
func checkGetRelativeURL(relativeURI string, ctxURL string) string {
	// Prepend web relative URL to "Lists/ListPath" URIs
	if relativeURI != "" {
		if string([]rune(relativeURI)[0]) != "/" {
			absoluteURL := getPriorEndpoint(ctxURL, "/_api")
			relativeURL := getRelativeURL(absoluteURL)
			relativeURI = fmt.Sprintf("%s/%s", relativeURL, relativeURI)
		}
	} else {
		panic("relativeURI is empty")
	}

	return relativeURI
}
```

it panics `panic: relativeURI is empty` as expected

**Versions**
SharePoint 2019

**To Reproduce**
Use site url that does not have .com
ex: `https://sharepointHost:8080/sites/TestSite` 
```json
{
    "siteUrl": "https://www.contoso/sites/test",
    "username": "contoso\\john.doe",
    "password": "this-is-not-a-real-password"
}
```

and call function `EnsureFolderByPath`

```go
sp.Web().EnsureFolderByPath("/Test Path") // doesn't panic if "Test Path" does not have "/" prefix
```

**Expected behavior**
No runtime panic, handling empty string correctly

**Screenshots**
```shell
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/koltyakov/gosip/api.checkGetRelativeURL({0x6dc6c7, 0x0}, {0xc0001200f0, 0x27})
        /go/pkg/mod/github.com/koltyakov/gosip@v0.0.0-20231220150131-60203a6b7c36/api/utils.go:107 +0x14b
github.com/koltyakov/gosip/api.(*Web).GetFolderByPath(0xc000115320, {0x6dc6c7?, 0x2?})
        /go/pkg/mod/github.com/koltyakov/gosip@v0.0.0-20231220150131-60203a6b7c36/api/web.go:296 +0x3d
github.com/koltyakov/gosip/api.ensureFolder.func1({0x6dc6c7?, 0xc00020c060?})
        /go/pkg/mod/github.com/koltyakov/gosip@v0.0.0-20231220150131-60203a6b7c36/api/folder.go:194 +0x37
github.com/koltyakov/gosip/api.ensureFolder(0xc000115320, {0x6dc6c7, 0xa}, {0x6dc6c7, 0x0}, {0x6db70d, 0x6})
        /go/pkg/mod/github.com/koltyakov/gosip@v0.0.0-20231220150131-60203a6b7c36/api/folder.go:201 +0x355
github.com/koltyakov/gosip/api.ensureFolder(0xc000115320, {0x6dc6c7, 0xa}, {0x6dc6c7, 0xa}, {0x6db70d, 0x6})
        /go/pkg/mod/github.com/koltyakov/gosip@v0.0.0-20231220150131-60203a6b7c36/api/folder.go:209 +0x42d
github.com/koltyakov/gosip/api.(*Web).EnsureFolderByPath(...)
        /go/pkg/mod/github.com/koltyakov/gosip@v0.0.0-20231220150131-60203a6b7c36/api/web.go:319
main.main()
        /root/app/main.go:441 +0x3e
exit status 2
```

**Additional context**
I'll create a pull request for a workaround (handling `if relativeURI != ""` ), not sure if I handled it correctly, so please review it.
Thanks

### PR DESCRIPTION
**Pull request by koltyakov**
The PR fixes #70 and adds corresponding edge case test.

### CODE REVIEW

**Comment by bangbaew** [comment]
Thank you, the program doesn't panic now, but it still does not work as expected when I'm trying to ensure a single folder
```go
sp.Web().EnsureFolderByPath("Original Requests") // gives Microsoft.SharePoint.Client.UnknownError from server
```

image

```go
sp.Web().EnsureFolderByPath("/Original Requests") // no error thrown, but nothing created
```

it works fine when it has at least one child path
```go
sp.Web().EnsureFolderByPath("Root Path/Child Path") // works just fine
```

**Comment by koltyakov** [comment]
Hey @bangbaew,

Not completely sure, how to repro. I'm checking different variations, using a test:

```golang
t.Run("EnsureFolderByPathEdgeCases", func(t *testing.T) {
  if envCode == "2013" {
    t.Skip("is not supported with SP 2013")
  }
  
  res, err := web.EnsureFolderByPath("Shared Documents")
  if err != nil {
    t.Error(err)
  }
  
  fmt.Printf("Folder Name: %s\n", string(res.Data().Name))
})
```

and it worked:

```bash
=== RUN   TestWeb
=== RUN   TestWeb/EnsureFolderByPathEdgeCases
Folder Name: Shared Documents
--- PASS: TestWeb (0.18s)
    --- PASS: TestWeb/EnsureFolderByPathEdgeCases (0.18s)
PASS
ok  	github.com/koltyakov/gosip/api	1.876s
```

Are you sure that your folder is actually an SPFolder but not a sub site (SPWeb)?

---

> sp.Web().EnsureFolderByPath("/Original Requests")

This is incorrect way of using the method. If the "Original Requests" is the folder name it should be prefixed with a document library path.

```golang
sp.Web().EnsureFolderByPath("DocLib/Original Requests") // DocLib should exist
```

or 

```golang
sp.Web().EnsureFolderByPath("/sites/site/DocLib/Original Requests") // DocLib should exist
```

**Comment by bangbaew** [comment]
> Hey @bangbaew,
> 
> Not completely sure, how to repro. I'm checking different variations, using a test:
> 
> ```go
> t.Run("EnsureFolderByPathEdgeCases", func(t *testing.T) {
>   if envCode == "2013" {
>     t.Skip("is not supported with SP 2013")
>   }
>   
>   res, err := web.EnsureFolderByPath("Shared Documents")
>   if err != nil {
>     t.Error(err)
>   }
>   
>   fmt.Printf("Folder Name: %s\n", string(res.Data().Name))
> })
> ```
> 
> and it worked:
> 
> ```shell
> === RUN   TestWeb
> === RUN   TestWeb/EnsureFolderByPathEdgeCases
> Folder Name: Shared Documents
> --- PASS: TestWeb (0.18s)
>     --- PASS: TestWeb/EnsureFolderByPathEdgeCases (0.18s)
> PASS
> ok  	github.com/koltyakov/gosip/api	1.876s
> ```
> 
> Are you sure that your folder is actually an SPFolder but not a sub site (SPWeb)?
> 
> > sp.Web().EnsureFolderByPath("/Original Requests")
> 
> This is incorrect way of using the method. If the "Original Requests" is the folder name it should be prefixed with a document library path.
> 
> ```go
> sp.Web().EnsureFolderByPath("DocLib/Original Requests") // DocLib should exist
> ```
> 
> or
> 
> ```go
> sp.Web().EnsureFolderByPath("/sites/site/DocLib/Original Requests") // DocLib should exist
> ```

I think it's a document library which is listed on the navigation bar of the page, so is it possible to ensure a document library with this function?
image

**Comment by koltyakov** [comment]
It could be anything added to quick launch menu. 😄 When you open it, what's the URL?

In this test `web.EnsureFolderByPath("Shared Documents")` "Shared Documents" is a document library and the method works just fine.

**Comment by bangbaew** [comment]
> It could be anything added to quick launch menu. 😄 When you open it, what's the URL?
> 
> In this test `web.EnsureFolderByPath("Shared Documents")` "Shared Documents" is a document library and the method works just fine.

The url when I clicked on a manually created document library is
`https://{Host}:{Port}/sites/{Site Name}/{Sub Site}/{Document Library}/Forms/AllItems.aspx`

my site url in the configuration is
`https://{Host}:{Port}/sites/{Site Name}/{Sub Site}`

**Comment by koltyakov** [comment]
Document Library (or a List) is not a folder. You can't create it using EnsureFolderByPath method.

If you have a Document Library and has to use/create a folder structure, this is the method to use.

You can create a library using:

```golang
newLib, err := sp.Web().Lists().Add("My Lib", map[string]interface{}{
  "BaseTemplate": 101, // Document Library
})
```

Yet, SharePoint Lists and Libraries provisioning is a bit complex topic. There is a lot you'd need to do with falling back to CSOM.

**Comment by bangbaew** [comment]
It works now!
Thank you so much.

**Pull request merged**
